version: '3.8'

services:
  backend:
    container_name: api_quadratic_backend
    image: cianoid/quadratic_equation:latest
    restart: always
    volumes:
      - api_quadratic_static_backend_value:/app/static/
      - api_quadratic_db_value:/app/db/
    env_file:
      - ./.env

  nginx:
    container_name: api_quadratic_nginx
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - api_quadratic_static_backend_value:/var/html/static_backend/
      - api_quadratic_logs_value:/var/logs/
    depends_on:
      - backend
volumes:
  api_quadratic_logs_value:
  api_quadratic_static_backend_value:
  api_quadratic_db_value: