version: '3.8'

services:
  backend:
    image: cianoid/quadratic_equation:latest
    restart: always
    volumes:
      - static_backend_value:/app/static/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_backend_value:/var/html/static_backend/
      - logs_value:/var/logs/
    depends_on:
      - backend
volumes:
  logs_value:
  static_backend_value: